### ISSUE TITLE
Proposal: rename

### ISSUE THREAD

**Issue by krancour** [lovethedrake/go-drake#51]
I'd like to propose renaming this repository (and the Go module) as "drake-go".

This would allow us, in the future, to host other language bindings in the same github org without one being treated as more important than the others.

I also think (correct me if I am wrong) that "drake-go" plays nicely with Go package/module conventions. i.e. I think the package would automatically be referenced as `drake` when imported.

**Comment by carolynvs** [comment]
The package name is not tied to the URL, and I don't think that go does any special suffix/prefix trimming on the word go. I haven't tried though to know for sure. What I would do is rename the repo and set the package declarations to be

```go
package drake
```

**Comment by krancour** [comment]
Package names aren't tied to URLs, but I think _module_ names are. That's how modules are located, is it not?

**Comment by carolynvs** [comment]
The best way to know is to make a test repo quick and find out!

**Comment by krancour** [comment]
Renamed to `go-drake` and everything that depends on it (`mallard` and `brigdrake`) are using the new coordinates without any issue.
